accounts/urls.py
from django.urls import path

from .views import (LoginView, ProfileView, RegisterView,
                    ForgotPasswordView, NewPasswordView,
                    LogoutView, VerificationView, VerifyPasswordChange)

app_name = 'accounts'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('signup', RegisterView.as_view(), name='register'),
    path('verification/<uidb64>/<token>', VerificationView.as_view(), name='verify'),
    path('forgot_password', ForgotPasswordView.as_view(),
         name='forgot_password'),
    path('verify_password_change/<uidb64>/<token>', VerifyPasswordChange.as_view(), name='verify_password_change'),
    path('new_password', NewPasswordView.as_view(), name='new_password'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('logout', LogoutView.as_view(), name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>MyAuth</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% block content %}  
    {% endblock content %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
   
</body>

</html>

templates/login.html
{% extends 'base.html' %} {% block content %}

<section
  class="d-flex justify-content-center align-items-center"
  style="font-family: Roboto, sans-serif"
>
  <div
    class="p-5 shadow-sm"
    style="
      background: #ffffff;
      border-radius: 10px;
      font-family: system-ui, -apple-system, 'Segoe UI', Roboto,
        'Helvetica Neue', Arial, 'Noto Sans', 'Liberation Sans', sans-serif,
        'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',
        'Noto Color Emoji';
    "
  >
    <h3 class="text-center">MyAuth Login</h3>
    <p class="text-center text-black-50 mb-4">
      Welcome! Enter Username and Password to login
    </p>
    
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close">
        </button>
        <span>{{ message }}</span>
      </div>
      {% endfor %}
      {% endif %}

    <form method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      <div class="mb-3">
        <label
          class="form-label text-black-50 form-label"
          for="usernameField"
          style="font-size: 14px"
          >USERNAME</label
        >
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-user"></i></span
          >{{ form.username }}
        </div>
        <small class="text-danger mb-2">{{ form.username.errors }}</small>
      </div>
      <div class="mb-2">
        <label
          class="form-label text-black-50 form-label"
          for="passwordField"
          style="font-size: 14px"
          >PASSWORD</label
        >
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-lock"></i></span
          >{{ form.password }}
          <span class="input-group-text"><i class="far fa-eye"></i></span>
        </div>
        <small class="text-danger mb-2">{{ form.password.errors }}</small>
      </div>
      <div class="d-flex justify-content-between mb-4">
        <div class="form-check">
         {{ form.remember_me }}
         <label class="form-check-label text-black-50" for="formCheck-1"
            >Remember Me</label
          >
        </div>
        <a class="forgot" href="{% url 'accounts:forgot_password' %}">Forgot Password</a>
      </div>
      <button class="btn btn-primary mb-3 submit" type="submit">LOGIN</button
      ><a
        class="btn btn-light link-primary shadow-sm submit signup"
        role="button"
        href="{% url 'accounts:register' %}"
        >SIGN UP</a
      >
    </form>
  </div>
</section>
{% endblock content %}

templates/new_password.html
  {% extends 'base.html' %}
  
  {% block content %}
  <section class="d-flex justify-content-center align-items-center" style="font-family: Roboto, sans-serif;">
    <div class="p-5 shadow-sm" style="background: #ffffff;border-radius: 10px;font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">
        <h3 class="text-center">MyAuth</h3>
        <p class="text-center text-black-50 mb-4">Welcome! Enter new password for myauth account</p>
        <form method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label class="form-label text-black-50 form-label" for="passwordField" style="font-size: 14px;">PASSWORD</label>
                <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                    {{ form.password1 }}
                    <span class="input-group-text"><i class="far fa-eye"></i></span>
                </div>
            </div>
            <div class="mb-4">
                <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                    {{ form.password2 }}                    
                    <span class="input-group-text"><i class="far fa-eye"></i></span>
                </div>
                <small class="text-danger mb-2">{{ form.password2.errors }}</small>
            </div>
            <button class="btn btn-primary mb-3 submit" type="submit">Create password</button>
        </form>
    </div>
</section>
  {% endblock content %}
      

templates/password_reset.html
{% extends 'base.html' %}

{% block content %}
<section class="d-flex justify-content-center align-items-center" style="font-family: Roboto, sans-serif;">
    <div class="p-5 shadow-sm" style="background: #ffffff;border-radius: 10px;font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">
        <h3 class="text-center">MyAuth</h3>
        <p class="text-center text-black-50 mb-4">Welcome! Enter email to reset myauth password</p>

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close">
          </button>
          <span>{{ message }}</span>
        </div>
        {% endfor %}
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div class="mb-3"><label class="form-label text-black-50 form-label" for="emailField" style="font-size: 14px;">EMAIL</label>
                <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                    <input class="form-control" type="email" name="email" id="emailField" placeholder="Enter your email">
                </div>
            </div>
            <button class="btn btn-primary mb-3 submit" type="submit">Submit</button>
        </form>
    </div>
</section>
{% endblock content %}
    
    

templates/profile.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<section
  class="d-flex justify-content-center align-items-center"
  style="font-family: Roboto, sans-serif"
>
  <div
    class="text-center p-5 shadow-sm"
    style="
      background: #ffffff;
      border-radius: 10px;
      font-family: system-ui, -apple-system, 'Segoe UI', Roboto,
        'Helvetica Neue', Arial, 'Noto Sans', 'Liberation Sans', sans-serif,
        'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',
        'Noto Color Emoji';
    "
  >
    <h4 class="text-center">Profile page</h4>
    <img
      class="rounded-circle img-fluid mb-2"
      src="{% static 'img/profile_picture.jpg' %}"
      width="100"
      height="100"
    />
    <p class="text-center text-black-50 mb-1">
      Welcome {{ request.user.username }}!
    </p>
    <p class="text-center text-black-50 mb-4">
      You have successfully logged into myauth app
    </p>
    <a class="btn btn-secondary mb-3 submit" role="button" href="{% url 'accounts:logout' %}">Logout</a>
  </div>
</section>
{% endblock content %}

templates/register.html
{% extends 'base.html' %} 
{% block content %}
<section
  class="d-flex justify-content-center align-items-center"
  style="font-family: Roboto, sans-serif"
>
  <div
    class="p-5 shadow-sm"
    style="
      background: #ffffff;
      border-radius: 10px;
      font-family: system-ui, -apple-system, 'Segoe UI', Roboto,
        'Helvetica Neue', Arial, 'Noto Sans', 'Liberation Sans', sans-serif,
        'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',
        'Noto Color Emoji';
    "
  >
    <h3 class="text-center">MyAuth SignUp</h3>
    <p class="text-center text-black-50 mb-4">
      Welcome! Enter details to create myauth account
    </p>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close">
      </button>
      <span>{{ message }}</span>
    </div>
    {% endfor %}
    {% endif %}

    <form method="post" action="{% url 'accounts:register' %}">
      {% csrf_token %}
      <div class="mb-2">
        <label
          class="form-label text-black-50 form-label"
          for="usernameField"
          style="font-size: 14px"
          >USERNAME</label
        >
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-user"></i></span
          > {{ form.username }}
        </div>
      </div>
      <small class="text-danger mb-2">{{ form.username.errors }}</small>

      <div class="mb-2">
        <label
          class="form-label text-black-50 form-label"
          for="emailField"
          style="font-size: 14px"
          >EMAIL</label
        >
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-envelope"></i></span>
          {{ form.email }}
        </div>
        <small class="text-danger mb-2">{{ form.email.errors }}</small>
      </div>

      <div class="mb-2">
        <label
          class="form-label text-black-50 form-label"
          for="passwordField"
          style="font-size: 14px"
          >PASSWORD</label
        >
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-lock"></i></span
          >{{ form.password1 }}
          <span class="input-group-text"><i class="far fa-eye"></i></span>
        </div>
      </div>
      <div class="mb-2">
        <div class="input-group">
          <span class="input-group-text"><i class="fas fa-lock"></i></span
          >{{ form.password2 }}
          <span class="input-group-text"><i class="far fa-eye"></i></span>
        </div>
      </div>
      <small class="text-danger mb-0">{{ form.password1.errors }}</small>
      <small class="text-danger mb-2">{{ form.password2.errors }}</small>
      <button class="btn btn-primary mb-3 submit" type="submit">Sign Up</button>
    </form>
    <p class="text-center text-black-50 mb-4">
      Already have an account, <a style="text-decoration: none;" href="{% url 'accounts:login' %}">Login</a>
    </p>
  </div>
</section>
{% endblock content %}